name: Golang build 1

on:
  push:
    branches:
      - '**'

env:
  version: 1.21.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go {{$env.version}}
        uses: actions/setup-go@v4
        with:
          go-version: {{$env.version}}
      - name: Build
        run: go build -o ../bin/workshop -v ./...
        working-directory: workshop-service
      - name: Upload /bin folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workshop
          path: bin/
          retention-days: 1

