name: Golang build 1

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Build
      run: cd workshop-service && go build ov ../workshop-service

    - name: Test
      run: go test -v ./workshop-service

